version: 2

jobs:
    # Build Cyclus
    build:
        docker:
            - image: cyclus/cyclus:latest
        working_directory: ~/cycamore
        steps:
            - checkout
            - run:
                name: Build Cycamore
                command: |
                    python install.py -j 2 --build-type=Release \
                    -DBLAS_LIBRARIES="/opt/conda/lib/libblas.so" \
                    -DLAPACK_LIBRARIES="/opt/conda/lib/liblapack.so"
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - save_cache:
                key: v1-repo-{{ checksum ".circle-sha" }}
                paths:
                  - /root


    # Update docker container
    deploy: # Cyclus/dev -> Cyclus:latest
        docker:
            - image: circleci/ruby:2.4-node
        working_directory: ~/cycamore
        steps:
            - checkout
            - run:
                name: Place the proper Dockerfile
                command: cp docker/develop-ci/Dockerfile .
            - setup_remote_docker
            - run:
                name: log into Docker
                command: |
                    docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: Build Docker container
                command: docker build --rm=false -t cyclus/cycamore:latest .
            - run:
                name: Push on DockerHub
                command: docker push cyclus/cycamore:latest # push to docker depot

    deploy_stable: # Cyclus/master -> Cyclus:stable
        docker:
            - image: circleci/ruby:2.4-node
        working_directory: ~/cycamore
        steps:
            - checkout
            - run:
                name: Place the proper Dockerfile
                command: cp docker/master-ci/Dockerfile .
            - setup_remote_docker
            - run:
                name: Log on DockerHub
                command: |
                  docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                name: Build Docker container
                command: docker build -t cyclus/cycamore:stable .
            - run:
                name: Push on DockerHub
                command: docker push cyclus/cycamore:stable # push to docker depot


    # Debian package generation (on master update)
    deb_generation:
        docker:
            - image: circleci/ruby:2.4-node
        working_directory: ~/cycamore
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Tag and Push on DockerHub
                no_output_timeout: "20m"
                command: |
                  docker/deb-ci/build_upload_deb.sh 14
                  docker/deb-ci/build_upload_deb.sh 16
    

    # Triggered by Cyclus               
    dev_against_cyclus_master:  ## Cycamore/dev against Cyclus/master
        docker:
            - image: cyclus/cyclus:master
        working_directory: ~/cycamore
        steps:
            - checkout
            - run:
                name: Build Docker Image
                command: |
                    python install.py -j 2 --build-type=Release \
                    -DBLAS_LIBRARIES="/opt/conda/lib/libblas.so" \
                    -DLAPACK_LIBRARIES="/opt/conda/lib/liblapack.so"
            - run:
                name: Unit Test
                command: /root/.local/bin/cycamore_unit_tests; exit $?
            - run:
                name: Install nosetest
                command: pip install nose
            - run:
                name: Nosetests
                command: nosetests -w ~/cycamore/tests; exit $?


    # Test JObs
    unit_test:
        docker:
            - image: cyclus/cyclus:latest
        working_directory: ~/root
        steps:
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                  - v1-repo-{{ checksum ".circle-sha" }}
            - run:
                name: Unit Test
                command: /root/.local/bin/cycamore_unit_tests; exit $?
    nosetest:
        docker:
            - image: cyclus/cyclus:latest
        working_directory: ~/root
        steps:
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                  - v1-repo-{{ checksum ".circle-sha" }}
            - run:
                name: Install nosetest
                command: pip install nose
            - run:
                name: Nosetests
                command: nosetests -w ~/cycamore/tests; exit $?

workflows:
    version: 2
    build_and_test:
        jobs:
            
            # on a pr // all branch
            - build
            - unit_test:
                requires:
                    - build
            - nosetest:
                requires:
                    - build
            
            # Merge on Develop
            - deploy_latest:
                filters:
                    branches:
                        only: develop
                requires:
                    - unit_test
                    - nosetest
            
            
            # Merge on Master
            - deploy_stable:
                filters:
                    branches:
                        only: master
                requires:
                    - unit_test
                    - nosetest

            - deb_generation:
                filters:
                    branches:
                        only: master
                requires:
                    - unit_test
                    - nosetest
